name = "ai-video-worker"
main = "src/index.ts"
compatibility_date = "2024-05-29"
compatibility_flags = ["nodejs_compat"]
account_id = "d30bed2763a23cf8eddf343ca192c5ff"

[env.production]
name = "ai-video-worker"
main = "src/index.ts"

[env.production.vars]
ENVIRONMENT = "production"
GITHUB_REPO_OWNER = "Dragontxl"
GITHUB_REPO_NAME = "vdproc2"
FRONTEND_URL = "https://ai-video-frontend-5xr.pages.dev"
ADMIN_URL = "https://ai-video-frontend-5xr.pages.dev"
R2_PUBLIC_URL = ""

[[env.production.d1_databases]]
binding = "DB"
database_name = "ai-video-db"
database_id = "75b5c974-04a5-4b27-9520-c5e3349903e4"

[[env.production.r2_buckets]]
binding = "R2"
bucket_name = "ai-video-bucket"

[[env.production.kv_namespaces]]
binding = "KV"
id = "2571947d6a3944a2a7f3e99f4679de10"

[env.production.triggers]
crons = ["*/5 * * * *"]

[vars]
ENVIRONMENT = "production"
GITHUB_REPO_OWNER = "Dragontxl"
GITHUB_REPO_NAME = "vdproc2"
FRONTEND_URL = "https://ai-video-frontend-5xr.pages.dev"
ADMIN_URL = "https://ai-video-frontend-5xr.pages.dev"

[[d1_databases]]
binding = "DB"
database_name = "ai-video-db"
database_id = "75b5c974-04a5-4b27-9520-c5e3349903e4"

[[r2_buckets]]
binding = "R2"
bucket_name = "ai-video-bucket"

[[kv_namespaces]]
binding = "KV"
id = "2571947d6a3944a2a7f3e99f4679de10"

[triggers]
crons = ["*/5 * * * *"]
